environment:
  nodejs_version: "8"

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/seoaapp/appveyor-discord-webhook/blob/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/seoaapp/appveyor-discord-webhook/blob/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
